import type { QuizQuestion, LearningTopic, ScanRecord } from '@/types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    scenario: 'You receive a message saying your account will be closed in 10 minutes unless you click a link. What should you do?',
    options: ['Click the link immediately', 'Reply with your password to verify', 'Verify the message through the official website', 'Forward the message to friends'],
    correctIndex: 2,
    explanation: 'Always verify account-related alerts by going directly to the official website or app. Legitimate services rarely give ultimatums with countdowns.',
    warningSign: 'Urgency + Phishing Link',
  },
  {
    id: 2,
    scenario: 'A social media account messages you saying you won a $500 gift card and just need to pay a $5 shipping fee. What is the biggest red flag?',
    options: ['The gift card amount is too small', 'You must pay a fee to receive a prize', 'They contacted you on social media', 'The gift card is in dollars'],
    correctIndex: 1,
    explanation: 'Real prizes never require upfront fees. Asking for payment before delivering a prize is one of the most common scam patterns.',
    warningSign: 'Upfront Payment + Unexpected Prize',
  },
  {
    id: 3,
    scenario: 'An online seller offers a brand-new iPhone for $150 and asks you to pay via wire transfer outside the platform. What should you do?',
    options: ['Buy it quickly before someone else does', 'Negotiate the price down further', 'Avoid the offer and report it', 'Pay half now and half on delivery'],
    correctIndex: 2,
    explanation: 'The price is unrealistically low and wire transfers offer no buyer protection. This combination strongly indicates a scam.',
    warningSign: 'Unusual Low Price + No Payment Protection',
  },
  {
    id: 4,
    scenario: 'You get a job offer for "Data Entry - $500/day" that requires a $200 training fee. What is the warning sign?',
    options: ['Data entry jobs don\'t pay well', 'Legitimate jobs don\'t charge training fees', 'The salary is listed per day', 'The job is remote'],
    correctIndex: 1,
    explanation: 'No legitimate employer charges you to work for them. Upfront fees for training or equipment are a hallmark of job scams.',
    warningSign: 'Upfront Payment + Unrealistic Earnings',
  },
  {
    id: 5,
    scenario: 'You receive an email from "security@yourbank-verify.com" asking you to confirm your login. What should you check first?',
    options: ['The email format looks professional', 'The sender\'s email domain for authenticity', 'Whether the email has a logo', 'The time the email was sent'],
    correctIndex: 1,
    explanation: 'The domain "yourbank-verify.com" is not your bank\'s real domain. Scammers use look-alike domains to trick you into trusting the email.',
    warningSign: 'Misleading Domain + Phishing',
  },
  {
    id: 6,
    scenario: 'Someone you met on a dating app says they\'re an "oil rig engineer" who needs you to receive a package for them. What is this likely?',
    options: ['A genuine request for help', 'A romance scam setup', 'A legitimate business opportunity', 'A test of your trustworthiness'],
    correctIndex: 1,
    explanation: 'Romance scammers often claim unusual jobs that explain why they can\'t meet. Requests to receive packages or money are money mule tactics.',
    warningSign: 'Romance Scam + Money Mule',
  },
  {
    id: 7,
    scenario: 'A friend\'s account sends you a link saying "Check this out!" with no context. What should you do?',
    options: ['Click it since it\'s from a friend', 'Verify with your friend through another channel first', 'Reply asking what it is', 'Share it with other friends'],
    correctIndex: 1,
    explanation: 'Your friend\'s account may have been compromised. Always verify unexpected links through a different communication channel.',
    warningSign: 'Account Takeover + Suspicious Link',
  },
  {
    id: 8,
    scenario: 'You see an ad for a crypto investment that "guarantees 200% returns in 7 days." What is the main red flag?',
    options: ['200% is a specific number', 'No investment can guarantee returns', 'Crypto is always risky', '7 days is too short'],
    correctIndex: 1,
    explanation: 'No legitimate investment guarantees returns, especially high percentages in short timeframes. This is a classic investment scam promise.',
    warningSign: 'Guaranteed Returns + Investment Scam',
  },
  {
    id: 9,
    scenario: 'Someone calls claiming to be from tech support saying your computer has a virus and they need remote access. What should you do?',
    options: ['Grant remote access to fix it', 'Give them your password', 'Hang up and contact official support', 'Ask them to prove it first'],
    correctIndex: 2,
    explanation: 'Tech support scammers create fake emergencies to gain access to your computer and financial accounts. Official support never cold-calls about viruses.',
    warningSign: 'Impersonation + Social Engineering',
  },
  {
    id: 10,
    scenario: 'A message says "Your package is delayed. Pay $1 to reschedule delivery" with a link. What should you check?',
    options: ['Whether you actually ordered something', 'The $1 amount seems reasonable', 'The link looks official', 'The message has tracking info'],
    correctIndex: 0,
    explanation: 'Package delivery scams rely on you not questioning whether you actually have a package. Always verify through your original order confirmation.',
    warningSign: 'Phishing + Social Engineering',
  },
];

export const LEARNING_TOPICS: LearningTopic[] = [
  {
    id: 'phishing',
    title: 'Phishing',
    icon: 'Fish',
    color: 'brand',
    shortDescription: 'Fake messages designed to steal your information.',
    whatIsIt: 'Phishing is when scammers send messages that look like they come from a trusted source — your bank, a social platform, or a delivery service — to trick you into clicking a link and entering personal information.',
    howItWorks: 'Scammers create convincing fake emails, texts, or websites. The message usually claims something urgent is happening with your account. When you click the link, you land on a fake website that captures your login details or financial information.',
    warningSigns: ['Urgency or threats about your account', 'Links that lead to unfamiliar domains', 'Generic greetings like "Dear Customer"', 'Requests for passwords or verification codes', 'Look-alike email addresses or URLs'],
    protection: ['Never click links in unexpected messages', 'Go to websites directly by typing the URL', 'Check the sender\'s full email address', 'Enable two-factor authentication', 'Report suspicious messages to the platform'],
    afterInteraction: 'If you entered your login on a fake page, change your password immediately on the real website. Enable two-factor authentication. Contact the organization that was impersonated. If you entered financial details, contact your bank right away.',
  },
  {
    id: 'fake-shops',
    title: 'Fake Online Shops',
    icon: 'ShoppingCart',
    color: 'warning',
    shortDescription: 'Fraudulent stores that take your money and never deliver.',
    whatIsIt: 'Fake online shops are websites designed to look like real stores. They advertise popular products at incredibly low prices to lure buyers, but either never ship anything or send counterfeit items.',
    howItWorks: 'Scammers create professional-looking websites with stolen product photos and logos. They advertise on social media, accept payment, and then disappear. Some ship cheap knockoffs instead of the advertised product.',
    warningSigns: ['Prices dramatically below market value', 'No physical address or company details', 'No return policy or unclear terms', 'Only accepts wire transfer or crypto', 'Website is very new with no reviews'],
    protection: ['Research the seller before buying', 'Check for independent reviews', 'Use credit cards or protected payment methods', 'Look for HTTPS and proper contact info', 'Be wary of social media ad prices that seem too good'],
    afterInteraction: 'Contact your payment provider immediately to dispute the charge. Report the website to the platform where you found the ad. Save screenshots and order confirmations as evidence. Monitor your accounts for unauthorized charges.',
  },
  {
    id: 'fake-jobs',
    title: 'Fake Job Offers',
    icon: 'Briefcase',
    color: 'accent',
    shortDescription: 'Employment scams that ask for money or personal data.',
    whatIsIt: 'Fake job offers are postings or messages that promise employment but are designed to steal your money, personal information, or use you as a money mule for illegal transfers.',
    howItWorks: 'Scammers post attractive job listings or message you directly. They may ask for application fees, training fees, or your bank details for "direct deposit." Some send you a fake check and ask you to forward part of the money — this is a money mule scheme.',
    warningSigns: ['Upfront fees for application or training', 'Unrealistically high pay for simple work', 'No verifiable company information', 'Communication only through messaging apps', 'Requests for sensitive info before hiring', 'Vague job descriptions'],
    protection: ['Research the company independently', 'Never pay to get a job', 'Verify the employer through official channels', 'Be cautious of work-from-home offers that seem too easy', 'Check if the company has a real website and reviews'],
    afterInteraction: 'Stop all communication with the "employer." If you shared bank details, contact your bank immediately. If you received and forwarded money, you may be a money mule — report this to authorities. Change passwords for any accounts you shared.',
  },
  {
    id: 'investment-scams',
    title: 'Investment Scams',
    icon: 'TrendingUp',
    color: 'success',
    shortDescription: 'Schemes promising guaranteed or unrealistic returns.',
    whatIsIt: 'Investment scams promise high or guaranteed returns with little or no risk. They may involve crypto, forex, stocks, or fake trading platforms designed to steal your money.',
    howItWorks: 'Scammers contact you through social media, messaging apps, or investment groups. They show fake profits and testimonials. Once you invest, you may see fake gains on a fake platform. When you try to withdraw, they ask for more fees or disappear entirely.',
    warningSigns: ['Guaranteed or very high returns', 'Pressure to invest quickly', "Claims of 'inside information'", 'Unregulated or unregistered platforms', 'Difficulty withdrawing funds', 'Requests for crypto or wire transfer'],
    protection: ['Only invest through regulated, licensed platforms', 'Be skeptical of guaranteed returns', 'Research any investment opportunity independently', 'Avoid investments promoted on social media', 'Check with financial regulators in your country'],
    afterInteraction: 'Stop sending money immediately. Report to your local financial regulator or fraud authority. Save all communications and transaction records. Do not believe anyone who says they can recover your money for a fee — that is a secondary scam.',
  },
  {
    id: 'giveaway-scams',
    title: 'Giveaway Scams',
    icon: 'Gift',
    color: 'danger',
    shortDescription: 'Fake prizes designed to collect fees or data.',
    whatIsIt: 'Giveaway scams tell you you\'ve won a prize, gift card, or lottery you never entered. They ask for a fee, your information, or for you to share the scam with friends to "claim" the prize.',
    howItWorks: 'You receive a message or see a post saying you won. To claim the prize, you must pay a "processing fee," provide personal information, or forward the message. The prize never arrives, and scammers may use your info for further fraud.',
    warningSigns: ['You didn\'t enter any contest', 'Upfront fees to claim a prize', 'No verifiable organizer or official page', 'Pressure to act quickly', 'Requests to share the "giveaway" with friends'],
    protection: ['Remember: you can\'t win a contest you didn\'t enter', 'Never pay fees to receive a prize', 'Verify the organizer through official channels', 'Be suspicious of giveaways on social media', 'Report fake giveaways to the platform'],
    afterInteraction: 'Do not send any money or information. If you already paid, contact your payment provider to dispute the transaction. Report the account to the platform. If you shared personal information, monitor your accounts for unusual activity.',
  },
  {
    id: 'account-takeover',
    title: 'Account Takeover',
    icon: 'UserX',
    color: 'brand',
    shortDescription: 'When scammers gain control of your accounts.',
    whatIsIt: 'Account takeover happens when a scammer gains access to your online account — email, social media, banking — and uses it to impersonate you, steal information, or scam your contacts.',
    howItWorks: 'Scammers get your password through phishing, data breaches, or credential stuffing. Once inside, they change the password and recovery options, then message your contacts with scams or access your linked financial accounts.',
    warningSigns: ['Unable to log into your account', 'Password or recovery info was changed', 'Friends report getting strange messages from you', 'Unfamiliar activity in your account history', 'Emails about logins from unknown devices or locations'],
    protection: ['Use strong, unique passwords for each account', 'Enable two-factor authentication everywhere', 'Don\'t click suspicious links in messages', 'Regularly check your account activity logs', 'Use a password manager to generate and store passwords'],
    afterInteraction: 'Try to recover your account through the platform\'s official recovery process. Change passwords for any accounts that share the same password. Notify your contacts that your account was compromised. Enable two-factor authentication once you regain access.',
  },
  {
    id: 'impersonation',
    title: 'Impersonation',
    icon: 'Copy',
    color: 'warning',
    shortDescription: 'Scammers pretending to be someone you trust.',
    whatIsIt: 'Impersonation is when scammers pretend to be a trusted person or organization — a bank, government agency, tech support, or even a friend — to gain your trust and manipulate you into sending money or information.',
    howItWorks: 'Scammers study their target and create convincing fake profiles, emails, or phone calls. They may know some of your details from data breaches. They use urgency and authority to pressure you into acting before you can verify their identity.',
    warningSigns: ['Unexpected contact from an "official"', 'Urgency or threats of consequences', 'Requests for payment or sensitive info', 'Contact through unofficial channels', 'Caller ID or email that looks slightly off', 'Refusal to let you verify independently'],
    protection: ['Always verify identity through official channels', 'Don\'t trust caller ID — it can be spoofed', 'Never share codes or passwords with anyone', 'Be suspicious of urgency and authority', 'Hang up and call back using an official number'],
    afterInteraction: 'If you sent money, contact your bank or payment provider immediately. If you shared personal information, monitor your accounts and consider a fraud alert. Report the impersonation to the real organization and to your local authorities.',
  },
  {
    id: 'romance-scams',
    title: 'Romance Scams',
    icon: 'Heart',
    color: 'danger',
    shortDescription: 'Fake relationships built to steal your money.',
    whatIsIt: 'Romance scams happen when someone creates a fake online identity to build a relationship with you, gain your trust, and eventually ask for money — often for "emergencies," "travel," or "investments."',
    howItWorks: 'Scammers create attractive fake profiles on dating apps or social media. They move fast, express strong feelings quickly, and avoid video calls or meeting in person. Once they\'ve built emotional trust, they fabricate a crisis and ask for money.',
    warningSigns: ['Professes love very quickly', 'Refuses video calls or in-person meetings', 'Claims to work overseas or on an "oil rig"', 'Eventually asks for money or packages', 'Profile photos look like a model or are inconsistent', 'Tries to move you to private messaging apps'],
    protection: ['Be cautious with people you haven\'t met in person', 'Insist on video calls early on', 'Reverse image search profile pictures', 'Never send money to someone you haven\'t met', 'Be wary of fast-moving emotional connections', 'Tell friends and family about online relationships'],
    afterInteraction: 'Stop all communication with the person. Do not send any more money. Report the profile to the dating platform. If you shared personal photos, be aware of potential sextortion — do not pay, and report it to authorities. Talk to someone you trust for support.',
  },
  {
    id: 'payment-scams',
    title: 'Payment Scams',
    icon: 'CreditCard',
    color: 'accent',
    shortDescription: 'Tricks designed to steal your payment information.',
    whatIsIt: 'Payment scams are schemes that steal your credit card details, bank information, or money through fake payment pages, fraudulent invoices, or by manipulating you into sending money through irreversible methods.',
    howItWorks: 'Scammers may create fake checkout pages, send fake invoices that look real, or convince you to send money via wire transfer, gift cards, or cryptocurrency — methods that are nearly impossible to reverse or trace.',
    warningSigns: ['Payment pages with unsecured HTTP connections', 'Requests for gift cards or crypto as payment', 'Wire transfer requests to unfamiliar accounts', 'Fake invoices for services you didn\'t use', 'Pressure to use non-standard payment methods'],
    protection: ['Always check for HTTPS on payment pages', 'Use credit cards for online purchases — they offer protection', 'Never pay with gift cards or crypto for services', 'Verify invoices through official channels', 'Be cautious of payment requests from new contacts'],
    afterInteraction: 'Contact your bank or card issuer immediately to report fraud and freeze the card. Dispute unauthorized charges. If you sent a wire transfer, contact the receiving bank and your local authorities. Monitor your credit report for unauthorized accounts.',
  },
  {
    id: 'social-engineering',
    title: 'Social Engineering',
    icon: 'Brain',
    color: 'success',
    shortDescription: 'Psychological manipulation to trick you.',
    whatIsIt: 'Social engineering is the art of manipulating people into giving up information or access. Instead of hacking systems, scammers hack human psychology — using trust, urgency, fear, or curiosity.',
    howItWorks: 'Scammers research you online, then craft a scenario that triggers an emotional response. They might pretend to be a colleague, create a fake emergency, or offer something irresistible. The goal is to make you act before you think critically.',
    warningSigns: ['Creates urgency or fear', 'Asks you to bypass normal procedures', 'Offers something that seems too good', 'Uses authority or intimidation', 'Asks for sensitive info in unusual ways', 'Builds rapport to lower your guard'],
    protection: ['Slow down — urgency is a red flag', 'Verify requests through a separate channel', 'Be cautious about what you share online', 'Question unexpected requests, even from "known" contacts', 'Don\'t let politeness override your security instincts', 'When in doubt, ask someone else for a second opinion'],
    afterInteraction: 'If you shared information, assess what was exposed and take corrective steps — change passwords, notify relevant parties, monitor accounts. If you realize the manipulation early, report the interaction to help protect others. Share your experience with friends and family.',
  },
];

export const SAMPLE_SCAN_HISTORY: ScanRecord[] = [
  {
    id: 'scan-001',
    type: 'message',
    typeLabel: 'Message',
    date: '2026-09-17T14:32:00Z',
    warningCount: 5,
    riskLevel: 'high',
    inputSummary: 'Bank account closure warning message',
  },
  {
    id: 'scan-002',
    type: 'link',
    typeLabel: 'Link',
    date: '2026-09-16T09:15:00Z',
    warningCount: 3,
    riskLevel: 'moderate',
    inputSummary: 'http://login-verify.account-update.net/login',
  },
  {
    id: 'scan-003',
    type: 'shopping',
    typeLabel: 'Shopping',
    date: '2026-09-15T18:45:00Z',
    warningCount: 2,
    riskLevel: 'moderate',
    inputSummary: 'iPhone 15 Pro - $149, wire transfer only',
  },
  {
    id: 'scan-004',
    type: 'job',
    typeLabel: 'Job',
    date: '2026-09-14T11:20:00Z',
    warningCount: 4,
    riskLevel: 'high',
    inputSummary: 'Data Entry - $500/day, $200 training fee',
  },
  {
    id: 'scan-005',
    type: 'prize',
    typeLabel: 'Prize',
    date: '2026-09-13T16:00:00Z',
    warningCount: 3,
    riskLevel: 'moderate',
    inputSummary: 'Lottery win notification - $10,000',
  },
  {
    id: 'scan-006',
    type: 'message',
    typeLabel: 'Message',
    date: '2026-09-12T08:10:00Z',
    warningCount: 1,
    riskLevel: 'low',
    inputSummary: 'Package delivery confirmation text',
  },
  {
    id: 'scan-007',
    type: 'link',
    typeLabel: 'Link',
    date: '2026-09-11T22:30:00Z',
    warningCount: 0,
    riskLevel: 'low',
    inputSummary: 'https://github.com/microsoft/vscode',
  },
];
